### ISSUE TITLE
Failed to start server on Mac

### ISSUE THREAD

**Issue by lesca** [lunixoid/dbibackend#4]
Click "Start Server" the error comes up in the terminal:

It looks like the script cannot find the device, no matter whether I connect my switch or not. 

```
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/Users/lesca/opt/anaconda3/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/Users/lesca/opt/anaconda3/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "dbibackend", line 170, in start_server
    connect_to_switch()
  File "dbibackend", line 149, in connect_to_switch
    dev = usb.core.find(idVendor=0x057E, idProduct=0x3000)
  File "/Users/lesca/opt/anaconda3/lib/python3.8/site-packages/usb/core.py", line 1299, in find
    raise NoBackendError('No backend available')
usb.core.NoBackendError: No backend available
```

**Comment by lunixoid** [comment]
Hi!
Could you provide more information about your environment?
- OS
- pyusb and usb versions (from pip freeze)

Do you have libusb installed? Because this exception usually occures when python could not detect native usb-backend.

**Comment by lesca** [comment]
@lunixoid , 

OS Version: 10.15.7
Python Version: 3.8.5

# pip freeze output
libusb==1.0.23b7
pyusb==1.1.1
usb==0.0.83.dev0

**Comment by lunixoid** [comment]
@lesca ,
Thank you. Could you try to install native libusb? F.e. via brew:
brew install libusb

**Comment by lesca** [comment]
Thanks @lunixoid , much better now. It now shows "waiting for switch" after clicking the "start server" button.

But once I connect switch, by selecting "Install title from usb" from DBI, I got message below from console:
It happens every time I connect switch to my Mac. 
Switch side, shows "waiting for dbibackend to be run ..." but nothing happens. 
Mac side, the dbibackend stops output new "waiting for switch" message.

```
Traceback (most recent call last):
  File "/Users/lesca/opt/anaconda3/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/Users/lesca/opt/anaconda3/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "dbibackend", line 170, in start_server
    connect_to_switch()
  File "dbibackend", line 156, in connect_to_switch
    dev.set_configuration()
  File "/Users/lesca/opt/anaconda3/lib/python3.8/site-packages/usb/core.py", line 905, in set_configuration
    self._ctx.managed_set_configuration(self, configuration)
  File "/Users/lesca/opt/anaconda3/lib/python3.8/site-packages/usb/core.py", line 113, in wrapper
    return f(self, *args, **kwargs)
  File "/Users/lesca/opt/anaconda3/lib/python3.8/site-packages/usb/core.py", line 159, in managed_set_configuration
    self.backend.set_configuration(self.handle, cfg.bConfigurationValue)
  File "/Users/lesca/opt/anaconda3/lib/python3.8/site-packages/usb/backend/libusb1.py", line 812, in set_configuration
    _check(self.lib.libusb_set_configuration(dev_handle.handle, config_value))
  File "/Users/lesca/opt/anaconda3/lib/python3.8/site-packages/usb/backend/libusb1.py", line 604, in _check
    raise USBError(_strerror(ret), ret, _libusb_errno[ret])
usb.core.USBError: [Errno 19] No such device (it may have been disconnected)
```

**Comment by lunixoid** [comment]
Seems libusb lose switch. Could you try another type-c cable or adapter?

**Comment by Spaider15** [comment]
faced with the same problem, first run server then plug in switch

**Comment by lunixoid** [comment]
Close outdated issue.

**Comment by erralb** [comment]
I'm having a similar issue : 

`python3 dbibackend-master/dbibackend/dbibackend.py ./games
Waiting for switch
Waiting for switch
Waiting for switch
Waiting for switch
Waiting for switch
Waiting for switch
Waiting for switch
Waiting for switch
Waiting for switch
Traceback (most recent call last):
  File "/Users/pierre/Switch/dbibackend-master/dbibackend/dbibackend.py", line 210, in <module>
    main()
  File "/Users/pierre/Switch/dbibackend-master/dbibackend/dbibackend.py", line 204, in main
    connect_to_switch(),
  File "/Users/pierre/Switch/dbibackend-master/dbibackend/dbibackend.py", line 173, in connect_to_switch
    switch_context = UsbContext(vid=0x057E, pid=0x3000)
  File "/Users/pierre/Switch/dbibackend-master/dbibackend/dbibackend.py", line 42, in __init__
    dev.set_configuration()
  File "/usr/local/lib/python3.9/site-packages/usb/core.py", line 915, in set_configuration
    self._ctx.managed_set_configuration(self, configuration)
  File "/usr/local/lib/python3.9/site-packages/usb/core.py", line 113, in wrapper
    return f(self, *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/usb/core.py", line 159, in managed_set_configuration
    self.backend.set_configuration(self.handle, cfg.bConfigurationValue)
  File "/usr/local/lib/python3.9/site-packages/usb/backend/libusb1.py", line 812, in set_configuration
    _check(self.lib.libusb_set_configuration(dev_handle.handle, config_value))
  File "/usr/local/lib/python3.9/site-packages/usb/backend/libusb1.py", line 604, in _check
    raise USBError(_strerror(ret), ret, _libusb_errno[ret])
usb.core.USBError: [Errno 19] No such device (it may have been disconnected)`

Weird thing is it works sometimes and sometimes not. I tried different cables

**Comment by jyooi** [comment]
For those who are using m1 mac, you might need to run the python3 with ```py arch -x86_64 python3 dbibackend.py ./list```

**Comment by asyba** [comment]
same issues No backend available

**Comment by lunixoid** [comment]
> same issues No backend available
Do you have libusb installed on you Mac?

**Comment by loloop** [comment]
Managed to make it work by running the command to create the symlink I found here: https://github.com/pyusb/pyusb/issues/355#issuecomment-1214444040

**Comment by pcasaretto** [comment]
Using a different cable solved usb.core.USBError for me

**Comment by ghost** [comment]
I just discovered this method right now and it is the best solution I have found only in Windows from what I see, so good luck and I hope it works for you to save hours of searching.
https://www.youtube.com/watch?v=lhz2zjjlskU

**Comment by maxijayme** [comment]
> I just discovered this method right now and it is the best solution I have found only in Windows from what I see, so good luck and I hope it works for you to save hours of searching. https://www.youtube.com/watch?v=lhz2zjjlskU

This is a great solution. You can install the DBI driver using a Zading. I did it in windows and it worked. 
It's necesary to initialize DBI and start it with Install title from DBIbackend and then conect the switch to the computer, so Zading reconize DBI
